# Generated by Django 2.1.2 on 2018-11-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('profile_picture', models.CharField(max_length=200)),
                ('cover_picture', models.CharField(max_length=200)),
                ('interests', models.CharField(max_length=300)),
                ('biography', models.TextField()),
            ],
        ),
    ]
