# Generated by Django 2.1.2 on 2018-11-30 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20181109_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cover_picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
