# Generated by Django 2.1.2 on 2018-11-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20181130_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cover_picture',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_picture'),
        ),
    ]
