# Generated by Django 2.1.2 on 2018-11-30 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20181129_2233'),
        ('webapp', '0008_auto_20181130_2050'),
    ]

    operations = [
    ]
