# Generated by Django 2.1.2 on 2018-11-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_merge_20181130_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='biography',
            field=models.TextField(default="Hey there, I'm using weHeart to make some friends!"),
        ),
    ]
