# Generated by Django 2.1.2 on 2018-12-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20181130_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_picture',
            field=models.ImageField(default='default_cover.png', upload_to='cover_picture'),
        ),
    ]
