# Generated by Django 2.1.2 on 2018-12-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_userprofile_cover_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cover_picture',
        ),
    ]
