# Generated by Django 2.1.2 on 2018-12-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20181205_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='biography',
            field=models.TextField(default="Hey there, I'm using weHeart to make some friends!"),
        ),
    ]
