# Generated by Django 2.1.2 on 2018-12-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20181206_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='biography',
            field=models.TextField(blank=True, default="Hey there, I'm using weHeart to make some friends!"),
        ),
    ]
