# Generated by Django 2.1.2 on 2018-12-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_userprofile_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='biography',
            field=models.TextField(default='mi mamamemima', null=True),
        ),
    ]
