# Generated by Django 2.1.2 on 2018-12-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_auto_20181206_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_picture',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_picture'),
        ),
    ]
